

version: 2.1

# Define the jobs we want to run for this project
jobs:
  initialize:
    docker:
      - image: hashicorp/terraform
    working_directory: ~/tf-class-repo
    steps:      
      - run: 
          name: present_working
          command: 'pwd'
#       - run: 
#           name: list
#           command: 'ls ~/tf-class-repo'
      - run: 
          name: go into dev
          command: 'cd ./dev && terraform init'
      - run: 
          name: init
          command: terraform init
      
  plan:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: cd dev
      - run: terraform plan
  apply:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: cd dev
      - run: terraform apply

# Orchestrate our job run sequence
workflows:
  init_and_plan:
    jobs:
      - initialize
      - plan:
          requires:
            - initialize
      - apply:
          requires:
            - plan
      - hold:
          type: approval
          requires:
            - plan
            
