

version: 2.1
orbs:
  terraform: "circleci/terraform@3.2.0"
# Define the jobs we want to run for this project
jobs:
  initialize: &init
    docker:
      - image: hashicorp/terraform
    working_directory: ~/tf-class-repo
    steps:      
      - checkout
      - run: 
          name: present_working_2
          command: 'cd dev && terraform init && terraform plan -out=output.tfplan'
      - persist_to_workspace:
          root: ~/tf-class-repo
          paths: dev/output.tfplan
      
  apply:
    docker:
      - image: hashicorp/terraform
    working_directory: ~/tf-class-repo
    steps:
      - checkout
#       - attach_workspace:
#            at: ~/tf-class-repo
      - run: cd dev && terraform init && terraform apply --auto-aprove

# Orchestrate our job run sequence
workflows:
  init_and_plan:
    jobs:
      - initialize
      - apply:
          requires:
            - initialize
      - hold:
          type: approval
          requires:
            - initialize
            
