version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: main
          requires:
            - terraform/plan















































# version: 2.1

# # Define the jobs we want to run for this project
# jobs:
#   init:
#     docker:
#       - image: hashicorp/terraform
#     working_directory: ~/tf-class-repo
#     steps:      
#       - run: ls
#       - run: pwd
#       - run: ls tf-class-repo/dev
#       - run: terraform init 
      
#   plan:
#     docker:
#       - image: hashicorp/terraform
#     steps:
#       - checkout
#       - run: cd dev
#       - run: terraform plan
#   apply:
#     docker:
#       - image: hashicorp/terraform
#     steps:
#       - checkout
#       - run: cd dev
#       - run: terraform apply

# # Orchestrate our job run sequence
# workflows:
#   init_and_plan:
#     jobs:
#       - init
#       - plan:
#           requires:
#             - init
#       - apply:
#           requires:
#             - plan
#       - hold:
#           type: approval
#           requires:
#             - plan
            
