version: 2.1

# Define the jobs we want to run for this project
jobs:
  init:
    docker:
      - image: hashicorp/terraform
    working_directory: ~/tf-class-repo/dev
    steps:      
      - checkout
      - run: ls
#       - run: cd /dev
      - run: pwd
      - run: ls tf-class-repo/dev
      - run: terraform -chdir=tf-class-repo/dev init 
      
  plan:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: cd dev
      - run: terraform plan
  apply:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: cd dev
      - run: terraform apply

# Orchestrate our job run sequence
workflows:
  init_and_plan:
    jobs:
      - init
      - plan:
          requires:
            - init
      - apply:
          requires:
            - plan
      - hold:
          type: approval
          requires:
            - plan
            
